include: package:serverpod_lints/public.yaml

analyzer:
  language:
    strict-raw-types: false

linter:
  rules:
    avoid_relative_lib_imports: true
    prefer_relative_imports: true
    public_member_api_docs: false # TODO: This is temporary until we get closer to release
