// GENERATED by tool/generate_header_names.dart from tool/header_names.txt.
// Do not edit by hand.

import 'dart:typed_data';

/// An interned HTTP header name.
///
/// Known names have a stable small [id], so a store can index them without
/// hashing strings, and compare them by [id] alone. An unknown name has id
/// -1 and compares by its lowercase text, so it still works as a map key.
///
/// Names are ASCII case-insensitive on the wire (RFC 9110 5.1). [lower] is
/// the canonical form. The [id] of a known name is part of the public API
/// and never changes.
final class HeaderName {
  /// Stable small id of a known name, or -1.
  final int id;

  /// The canonical lowercase name.
  final String lower;

  const HeaderName._(this.id, this.lower);

  /// A name outside the known table, from a lowercase token.
  ///
  /// Use [lookup] for a name that may be known or may carry uppercase. This
  /// constructor exists for const contexts such as a `const HeaderAccessor`
  /// on a custom header.
  const HeaderName.custom(this.lower)
    : id = -1,
      assert(lower != '', 'A header name is not empty');

  /// The known name for [name], or a fresh unknown name.
  ///
  /// Throws [FormatException] when [name] is not an HTTP token.
  static HeaderName lookup(final String name) {
    final known = _lookupUnits(name);
    if (known != null) return known;
    if (!isToken(name)) {
      throw FormatException('Invalid header name', name);
    }
    return HeaderName._(-1, name.toLowerCase());
  }

  /// The known name spelled by `bytes[start..end)`, or null.
  ///
  /// Allocates nothing. Adapters call this while indexing a request head.
  static HeaderName? lookupBytes(
    final Uint8List bytes,
    final int start,
    final int end,
  ) {
    switch (end - start) {
      case 2:
        if (_eqBytes(bytes, start, 'te')) return te;
      case 3:
        if (_eqBytes(bytes, start, 'age')) return age;
        if (_eqBytes(bytes, start, 'via')) return via;
        if (_eqBytes(bytes, start, 'dnt')) return dnt;
        if (_eqBytes(bytes, start, 'nel')) return nel;
      case 4:
        if (_eqBytes(bytes, start, 'host')) return host;
        if (_eqBytes(bytes, start, 'from')) return from;
        if (_eqBytes(bytes, start, 'etag')) return etag;
        if (_eqBytes(bytes, start, 'vary')) return vary;
        if (_eqBytes(bytes, start, 'date')) return date;
        if (_eqBytes(bytes, start, 'link')) return link;
      case 5:
        if (_eqBytes(bytes, start, 'range')) return range;
        if (_eqBytes(bytes, start, 'allow')) return allow;
      case 6:
        if (_eqBytes(bytes, start, 'cookie')) return cookie;
        if (_eqBytes(bytes, start, 'accept')) return accept;
        if (_eqBytes(bytes, start, 'expect')) return expect;
        if (_eqBytes(bytes, start, 'origin')) return origin;
        if (_eqBytes(bytes, start, 'server')) return server;
        if (_eqBytes(bytes, start, 'pragma')) return pragma;
      case 7:
        if (_eqBytes(bytes, start, 'upgrade')) return upgrade;
        if (_eqBytes(bytes, start, 'expires')) return expires;
        if (_eqBytes(bytes, start, 'trailer')) return trailer;
        if (_eqBytes(bytes, start, 'referer')) return referer;
        if (_eqBytes(bytes, start, 'alt-svc')) return altSvc;
        if (_eqBytes(bytes, start, 'sec-gpc')) return secGpc;
        if (_eqBytes(bytes, start, 'warning')) return warning;
      case 8:
        if (_eqBytes(bytes, start, 'if-match')) return ifMatch;
        if (_eqBytes(bytes, start, 'if-range')) return ifRange;
        if (_eqBytes(bytes, start, 'location')) return location;
        if (_eqBytes(bytes, start, 'alt-used')) return altUsed;
        if (_eqBytes(bytes, start, 'priority')) return priority;
      case 9:
        if (_eqBytes(bytes, start, 'forwarded')) return forwarded;
        if (_eqBytes(bytes, start, 'expect-ct')) return expectCt;
        if (_eqBytes(bytes, start, 'report-to')) return reportTo;
        if (_eqBytes(bytes, start, 'save-data')) return saveData;
        if (_eqBytes(bytes, start, 'sec-ch-ua')) return secChUa;
        if (_eqBytes(bytes, start, 'x-real-ip')) return xRealIp;
      case 10:
        if (_eqBytes(bytes, start, 'user-agent')) return userAgent;
        if (_eqBytes(bytes, start, 'connection')) return connection;
        if (_eqBytes(bytes, start, 'set-cookie')) return setCookie;
        if (_eqBytes(bytes, start, 'early-data')) return earlyData;
        if (_eqBytes(bytes, start, 'keep-alive')) return keepAlive;
      case 11:
        if (_eqBytes(bytes, start, 'retry-after')) return retryAfter;
        if (_eqBytes(bytes, start, 'accept-post')) return acceptPost;
        if (_eqBytes(bytes, start, 'content-md5')) return contentMd5;
      case 12:
        if (_eqBytes(bytes, start, 'content-type')) return contentType;
        if (_eqBytes(bytes, start, 'max-forwards')) return maxForwards;
        if (_eqBytes(bytes, start, 'x-powered-by')) return xPoweredBy;
        if (_eqBytes(bytes, start, 'accept-patch')) return acceptPatch;
        if (_eqBytes(bytes, start, 'x-csrf-token')) return xCsrfToken;
        if (_eqBytes(bytes, start, 'x-request-id')) return xRequestId;
      case 13:
        if (_eqBytes(bytes, start, 'authorization')) return authorization;
        if (_eqBytes(bytes, start, 'if-none-match')) return ifNoneMatch;
        if (_eqBytes(bytes, start, 'cache-control')) return cacheControl;
        if (_eqBytes(bytes, start, 'content-range')) return contentRange;
        if (_eqBytes(bytes, start, 'last-modified')) return lastModified;
        if (_eqBytes(bytes, start, 'accept-ranges')) return acceptRanges;
        if (_eqBytes(bytes, start, 'server-timing')) return serverTiming;
      case 14:
        if (_eqBytes(bytes, start, 'content-length')) return contentLength;
        if (_eqBytes(bytes, start, 'sec-fetch-dest')) return secFetchDest;
        if (_eqBytes(bytes, start, 'sec-fetch-mode')) return secFetchMode;
        if (_eqBytes(bytes, start, 'sec-fetch-site')) return secFetchSite;
        if (_eqBytes(bytes, start, 'accept-charset')) return acceptCharset;
      case 15:
        if (_eqBytes(bytes, start, 'accept-encoding')) return acceptEncoding;
        if (_eqBytes(bytes, start, 'accept-language')) return acceptLanguage;
        if (_eqBytes(bytes, start, 'x-forwarded-for')) return xForwardedFor;
        if (_eqBytes(bytes, start, 'referrer-policy')) return referrerPolicy;
        if (_eqBytes(bytes, start, 'clear-site-data')) return clearSiteData;
        if (_eqBytes(bytes, start, 'x-frame-options')) return xFrameOptions;
      case 16:
        if (_eqBytes(bytes, start, 'content-encoding')) return contentEncoding;
        if (_eqBytes(bytes, start, 'content-language')) return contentLanguage;
        if (_eqBytes(bytes, start, 'content-location')) return contentLocation;
        if (_eqBytes(bytes, start, 'www-authenticate')) return wwwAuthenticate;
        if (_eqBytes(bytes, start, 'proxy-connection')) return proxyConnection;
        if (_eqBytes(bytes, start, 'sec-ch-ua-mobile')) return secChUaMobile;
        if (_eqBytes(bytes, start, 'x-forwarded-host')) return xForwardedHost;
        if (_eqBytes(bytes, start, 'x-forwarded-port')) return xForwardedPort;
        if (_eqBytes(bytes, start, 'x-requested-with')) return xRequestedWith;
        if (_eqBytes(bytes, start, 'x-xss-protection')) return xXssProtection;
      case 17:
        if (_eqBytes(bytes, start, 'if-modified-since')) return ifModifiedSince;
        if (_eqBytes(bytes, start, 'transfer-encoding'))
          return transferEncoding;
        if (_eqBytes(bytes, start, 'sec-websocket-key')) return secWebsocketKey;
        if (_eqBytes(bytes, start, 'x-forwarded-proto')) return xForwardedProto;
      case 18:
        if (_eqBytes(bytes, start, 'proxy-authenticate'))
          return proxyAuthenticate;
        if (_eqBytes(bytes, start, 'permissions-policy'))
          return permissionsPolicy;
        if (_eqBytes(bytes, start, 'sec-ch-ua-platform'))
          return secChUaPlatform;
      case 19:
        if (_eqBytes(bytes, start, 'if-unmodified-since'))
          return ifUnmodifiedSince;
        if (_eqBytes(bytes, start, 'proxy-authorization'))
          return proxyAuthorization;
        if (_eqBytes(bytes, start, 'content-disposition'))
          return contentDisposition;
        if (_eqBytes(bytes, start, 'authentication-info'))
          return authenticationInfo;
        if (_eqBytes(bytes, start, 'timing-allow-origin'))
          return timingAllowOrigin;
      case 20:
        if (_eqBytes(bytes, start, 'sec-websocket-accept'))
          return secWebsocketAccept;
      case 21:
        if (_eqBytes(bytes, start, 'sec-websocket-version'))
          return secWebsocketVersion;
      case 22:
        if (_eqBytes(bytes, start, 'access-control-max-age'))
          return accessControlMaxAge;
        if (_eqBytes(bytes, start, 'sec-websocket-protocol'))
          return secWebsocketProtocol;
        if (_eqBytes(bytes, start, 'x-content-type-options'))
          return xContentTypeOptions;
        if (_eqBytes(bytes, start, 'x-dns-prefetch-control'))
          return xDnsPrefetchControl;
      case 23:
        if (_eqBytes(bytes, start, 'content-security-policy'))
          return contentSecurityPolicy;
      case 24:
        if (_eqBytes(bytes, start, 'sec-websocket-extensions'))
          return secWebsocketExtensions;
      case 25:
        if (_eqBytes(bytes, start, 'strict-transport-security'))
          return strictTransportSecurity;
        if (_eqBytes(bytes, start, 'upgrade-insecure-requests'))
          return upgradeInsecureRequests;
      case 26:
        if (_eqBytes(bytes, start, 'cross-origin-opener-policy'))
          return crossOriginOpenerPolicy;
      case 27:
        if (_eqBytes(bytes, start, 'access-control-allow-origin'))
          return accessControlAllowOrigin;
      case 28:
        if (_eqBytes(bytes, start, 'access-control-allow-methods'))
          return accessControlAllowMethods;
        if (_eqBytes(bytes, start, 'access-control-allow-headers'))
          return accessControlAllowHeaders;
        if (_eqBytes(bytes, start, 'cross-origin-resource-policy'))
          return crossOriginResourcePolicy;
        if (_eqBytes(bytes, start, 'cross-origin-embedder-policy'))
          return crossOriginEmbedderPolicy;
      case 29:
        if (_eqBytes(bytes, start, 'access-control-request-method'))
          return accessControlRequestMethod;
        if (_eqBytes(bytes, start, 'access-control-expose-headers'))
          return accessControlExposeHeaders;
      case 30:
        if (_eqBytes(bytes, start, 'access-control-request-headers'))
          return accessControlRequestHeaders;
      case 32:
        if (_eqBytes(bytes, start, 'access-control-allow-credentials'))
          return accessControlAllowCredentials;
      case 35:
        if (_eqBytes(bytes, start, 'content-security-policy-report-only'))
          return contentSecurityPolicyReportOnly;
    }
    return null;
  }

  /// Every known name, indexed by [id].
  static const known = <HeaderName>[
    contentType,
    contentLength,
    host,
    cookie,
    userAgent,
    accept,
    acceptEncoding,
    acceptLanguage,
    authorization,
    expect,
    from,
    ifMatch,
    ifModifiedSince,
    ifNoneMatch,
    ifRange,
    ifUnmodifiedSince,
    maxForwards,
    proxyAuthorization,
    range,
    te,
    upgrade,
    accessControlRequestHeaders,
    accessControlRequestMethod,
    forwarded,
    xForwardedFor,
    accessControlAllowCredentials,
    accessControlAllowOrigin,
    accessControlExposeHeaders,
    accessControlMaxAge,
    age,
    allow,
    cacheControl,
    connection,
    contentDisposition,
    contentEncoding,
    contentLanguage,
    contentLocation,
    contentRange,
    etag,
    expires,
    lastModified,
    location,
    proxyAuthenticate,
    retryAfter,
    trailer,
    transferEncoding,
    vary,
    wwwAuthenticate,
    xPoweredBy,
    acceptRanges,
    date,
    origin,
    referer,
    server,
    via,
    setCookie,
    strictTransportSecurity,
    contentSecurityPolicy,
    referrerPolicy,
    permissionsPolicy,
    accessControlAllowMethods,
    accessControlAllowHeaders,
    clearSiteData,
    secFetchDest,
    secFetchMode,
    secFetchSite,
    crossOriginResourcePolicy,
    crossOriginEmbedderPolicy,
    crossOriginOpenerPolicy,
    acceptCharset,
    acceptPatch,
    acceptPost,
    altSvc,
    altUsed,
    authenticationInfo,
    contentMd5,
    contentSecurityPolicyReportOnly,
    dnt,
    earlyData,
    expectCt,
    keepAlive,
    link,
    nel,
    pragma,
    priority,
    proxyConnection,
    reportTo,
    saveData,
    secChUa,
    secChUaMobile,
    secChUaPlatform,
    secGpc,
    secWebsocketAccept,
    secWebsocketExtensions,
    secWebsocketKey,
    secWebsocketProtocol,
    secWebsocketVersion,
    serverTiming,
    timingAllowOrigin,
    upgradeInsecureRequests,
    warning,
    xContentTypeOptions,
    xCsrfToken,
    xDnsPrefetchControl,
    xForwardedHost,
    xForwardedPort,
    xForwardedProto,
    xFrameOptions,
    xRealIp,
    xRequestId,
    xRequestedWith,
    xXssProtection,
  ];

  /// True if [s] is a non-empty HTTP token (RFC 9110 5.6.2).
  static bool isToken(final String s) {
    if (s.isEmpty) return false;
    for (var i = 0; i < s.length; i++) {
      if (!_isTchar(s.codeUnitAt(i))) return false;
    }
    return true;
  }

  /// True if [c] is a `tchar` code unit (RFC 9110 5.6.2).
  static bool isTchar(final int c) => _isTchar(c);

  @override
  bool operator ==(final Object other) =>
      other is HeaderName &&
      (id >= 0 ? id == other.id : (other.id < 0 && lower == other.lower));

  @override
  int get hashCode => id >= 0 ? id : lower.hashCode;

  @override
  String toString() => lower;

  /// `content-type`
  static const contentType = HeaderName._(0, 'content-type');

  /// `content-length`
  static const contentLength = HeaderName._(1, 'content-length');

  /// `host`
  static const host = HeaderName._(2, 'host');

  /// `cookie`
  static const cookie = HeaderName._(3, 'cookie');

  /// `user-agent`
  static const userAgent = HeaderName._(4, 'user-agent');

  /// `accept`
  static const accept = HeaderName._(5, 'accept');

  /// `accept-encoding`
  static const acceptEncoding = HeaderName._(6, 'accept-encoding');

  /// `accept-language`
  static const acceptLanguage = HeaderName._(7, 'accept-language');

  /// `authorization`
  static const authorization = HeaderName._(8, 'authorization');

  /// `expect`
  static const expect = HeaderName._(9, 'expect');

  /// `from`
  static const from = HeaderName._(10, 'from');

  /// `if-match`
  static const ifMatch = HeaderName._(11, 'if-match');

  /// `if-modified-since`
  static const ifModifiedSince = HeaderName._(12, 'if-modified-since');

  /// `if-none-match`
  static const ifNoneMatch = HeaderName._(13, 'if-none-match');

  /// `if-range`
  static const ifRange = HeaderName._(14, 'if-range');

  /// `if-unmodified-since`
  static const ifUnmodifiedSince = HeaderName._(15, 'if-unmodified-since');

  /// `max-forwards`
  static const maxForwards = HeaderName._(16, 'max-forwards');

  /// `proxy-authorization`
  static const proxyAuthorization = HeaderName._(17, 'proxy-authorization');

  /// `range`
  static const range = HeaderName._(18, 'range');

  /// `te`
  static const te = HeaderName._(19, 'te');

  /// `upgrade`
  static const upgrade = HeaderName._(20, 'upgrade');

  /// `access-control-request-headers`
  static const accessControlRequestHeaders = HeaderName._(
    21,
    'access-control-request-headers',
  );

  /// `access-control-request-method`
  static const accessControlRequestMethod = HeaderName._(
    22,
    'access-control-request-method',
  );

  /// `forwarded`
  static const forwarded = HeaderName._(23, 'forwarded');

  /// `x-forwarded-for`
  static const xForwardedFor = HeaderName._(24, 'x-forwarded-for');

  /// `access-control-allow-credentials`
  static const accessControlAllowCredentials = HeaderName._(
    25,
    'access-control-allow-credentials',
  );

  /// `access-control-allow-origin`
  static const accessControlAllowOrigin = HeaderName._(
    26,
    'access-control-allow-origin',
  );

  /// `access-control-expose-headers`
  static const accessControlExposeHeaders = HeaderName._(
    27,
    'access-control-expose-headers',
  );

  /// `access-control-max-age`
  static const accessControlMaxAge = HeaderName._(28, 'access-control-max-age');

  /// `age`
  static const age = HeaderName._(29, 'age');

  /// `allow`
  static const allow = HeaderName._(30, 'allow');

  /// `cache-control`
  static const cacheControl = HeaderName._(31, 'cache-control');

  /// `connection`
  static const connection = HeaderName._(32, 'connection');

  /// `content-disposition`
  static const contentDisposition = HeaderName._(33, 'content-disposition');

  /// `content-encoding`
  static const contentEncoding = HeaderName._(34, 'content-encoding');

  /// `content-language`
  static const contentLanguage = HeaderName._(35, 'content-language');

  /// `content-location`
  static const contentLocation = HeaderName._(36, 'content-location');

  /// `content-range`
  static const contentRange = HeaderName._(37, 'content-range');

  /// `etag`
  static const etag = HeaderName._(38, 'etag');

  /// `expires`
  static const expires = HeaderName._(39, 'expires');

  /// `last-modified`
  static const lastModified = HeaderName._(40, 'last-modified');

  /// `location`
  static const location = HeaderName._(41, 'location');

  /// `proxy-authenticate`
  static const proxyAuthenticate = HeaderName._(42, 'proxy-authenticate');

  /// `retry-after`
  static const retryAfter = HeaderName._(43, 'retry-after');

  /// `trailer`
  static const trailer = HeaderName._(44, 'trailer');

  /// `transfer-encoding`
  static const transferEncoding = HeaderName._(45, 'transfer-encoding');

  /// `vary`
  static const vary = HeaderName._(46, 'vary');

  /// `www-authenticate`
  static const wwwAuthenticate = HeaderName._(47, 'www-authenticate');

  /// `x-powered-by`
  static const xPoweredBy = HeaderName._(48, 'x-powered-by');

  /// `accept-ranges`
  static const acceptRanges = HeaderName._(49, 'accept-ranges');

  /// `date`
  static const date = HeaderName._(50, 'date');

  /// `origin`
  static const origin = HeaderName._(51, 'origin');

  /// `referer`
  static const referer = HeaderName._(52, 'referer');

  /// `server`
  static const server = HeaderName._(53, 'server');

  /// `via`
  static const via = HeaderName._(54, 'via');

  /// `set-cookie`
  static const setCookie = HeaderName._(55, 'set-cookie');

  /// `strict-transport-security`
  static const strictTransportSecurity = HeaderName._(
    56,
    'strict-transport-security',
  );

  /// `content-security-policy`
  static const contentSecurityPolicy = HeaderName._(
    57,
    'content-security-policy',
  );

  /// `referrer-policy`
  static const referrerPolicy = HeaderName._(58, 'referrer-policy');

  /// `permissions-policy`
  static const permissionsPolicy = HeaderName._(59, 'permissions-policy');

  /// `access-control-allow-methods`
  static const accessControlAllowMethods = HeaderName._(
    60,
    'access-control-allow-methods',
  );

  /// `access-control-allow-headers`
  static const accessControlAllowHeaders = HeaderName._(
    61,
    'access-control-allow-headers',
  );

  /// `clear-site-data`
  static const clearSiteData = HeaderName._(62, 'clear-site-data');

  /// `sec-fetch-dest`
  static const secFetchDest = HeaderName._(63, 'sec-fetch-dest');

  /// `sec-fetch-mode`
  static const secFetchMode = HeaderName._(64, 'sec-fetch-mode');

  /// `sec-fetch-site`
  static const secFetchSite = HeaderName._(65, 'sec-fetch-site');

  /// `cross-origin-resource-policy`
  static const crossOriginResourcePolicy = HeaderName._(
    66,
    'cross-origin-resource-policy',
  );

  /// `cross-origin-embedder-policy`
  static const crossOriginEmbedderPolicy = HeaderName._(
    67,
    'cross-origin-embedder-policy',
  );

  /// `cross-origin-opener-policy`
  static const crossOriginOpenerPolicy = HeaderName._(
    68,
    'cross-origin-opener-policy',
  );

  /// `accept-charset`
  static const acceptCharset = HeaderName._(69, 'accept-charset');

  /// `accept-patch`
  static const acceptPatch = HeaderName._(70, 'accept-patch');

  /// `accept-post`
  static const acceptPost = HeaderName._(71, 'accept-post');

  /// `alt-svc`
  static const altSvc = HeaderName._(72, 'alt-svc');

  /// `alt-used`
  static const altUsed = HeaderName._(73, 'alt-used');

  /// `authentication-info`
  static const authenticationInfo = HeaderName._(74, 'authentication-info');

  /// `content-md5`
  static const contentMd5 = HeaderName._(75, 'content-md5');

  /// `content-security-policy-report-only`
  static const contentSecurityPolicyReportOnly = HeaderName._(
    76,
    'content-security-policy-report-only',
  );

  /// `dnt`
  static const dnt = HeaderName._(77, 'dnt');

  /// `early-data`
  static const earlyData = HeaderName._(78, 'early-data');

  /// `expect-ct`
  static const expectCt = HeaderName._(79, 'expect-ct');

  /// `keep-alive`
  static const keepAlive = HeaderName._(80, 'keep-alive');

  /// `link`
  static const link = HeaderName._(81, 'link');

  /// `nel`
  static const nel = HeaderName._(82, 'nel');

  /// `pragma`
  static const pragma = HeaderName._(83, 'pragma');

  /// `priority`
  static const priority = HeaderName._(84, 'priority');

  /// `proxy-connection`
  static const proxyConnection = HeaderName._(85, 'proxy-connection');

  /// `report-to`
  static const reportTo = HeaderName._(86, 'report-to');

  /// `save-data`
  static const saveData = HeaderName._(87, 'save-data');

  /// `sec-ch-ua`
  static const secChUa = HeaderName._(88, 'sec-ch-ua');

  /// `sec-ch-ua-mobile`
  static const secChUaMobile = HeaderName._(89, 'sec-ch-ua-mobile');

  /// `sec-ch-ua-platform`
  static const secChUaPlatform = HeaderName._(90, 'sec-ch-ua-platform');

  /// `sec-gpc`
  static const secGpc = HeaderName._(91, 'sec-gpc');

  /// `sec-websocket-accept`
  static const secWebsocketAccept = HeaderName._(92, 'sec-websocket-accept');

  /// `sec-websocket-extensions`
  static const secWebsocketExtensions = HeaderName._(
    93,
    'sec-websocket-extensions',
  );

  /// `sec-websocket-key`
  static const secWebsocketKey = HeaderName._(94, 'sec-websocket-key');

  /// `sec-websocket-protocol`
  static const secWebsocketProtocol = HeaderName._(
    95,
    'sec-websocket-protocol',
  );

  /// `sec-websocket-version`
  static const secWebsocketVersion = HeaderName._(96, 'sec-websocket-version');

  /// `server-timing`
  static const serverTiming = HeaderName._(97, 'server-timing');

  /// `timing-allow-origin`
  static const timingAllowOrigin = HeaderName._(98, 'timing-allow-origin');

  /// `upgrade-insecure-requests`
  static const upgradeInsecureRequests = HeaderName._(
    99,
    'upgrade-insecure-requests',
  );

  /// `warning`
  static const warning = HeaderName._(100, 'warning');

  /// `x-content-type-options`
  static const xContentTypeOptions = HeaderName._(
    101,
    'x-content-type-options',
  );

  /// `x-csrf-token`
  static const xCsrfToken = HeaderName._(102, 'x-csrf-token');

  /// `x-dns-prefetch-control`
  static const xDnsPrefetchControl = HeaderName._(
    103,
    'x-dns-prefetch-control',
  );

  /// `x-forwarded-host`
  static const xForwardedHost = HeaderName._(104, 'x-forwarded-host');

  /// `x-forwarded-port`
  static const xForwardedPort = HeaderName._(105, 'x-forwarded-port');

  /// `x-forwarded-proto`
  static const xForwardedProto = HeaderName._(106, 'x-forwarded-proto');

  /// `x-frame-options`
  static const xFrameOptions = HeaderName._(107, 'x-frame-options');

  /// `x-real-ip`
  static const xRealIp = HeaderName._(108, 'x-real-ip');

  /// `x-request-id`
  static const xRequestId = HeaderName._(109, 'x-request-id');

  /// `x-requested-with`
  static const xRequestedWith = HeaderName._(110, 'x-requested-with');

  /// `x-xss-protection`
  static const xXssProtection = HeaderName._(111, 'x-xss-protection');

  static HeaderName? _lookupUnits(final String name) {
    switch (name.length) {
      case 2:
        if (_eqUnits(name, 'te')) return te;
      case 3:
        if (_eqUnits(name, 'age')) return age;
        if (_eqUnits(name, 'via')) return via;
        if (_eqUnits(name, 'dnt')) return dnt;
        if (_eqUnits(name, 'nel')) return nel;
      case 4:
        if (_eqUnits(name, 'host')) return host;
        if (_eqUnits(name, 'from')) return from;
        if (_eqUnits(name, 'etag')) return etag;
        if (_eqUnits(name, 'vary')) return vary;
        if (_eqUnits(name, 'date')) return date;
        if (_eqUnits(name, 'link')) return link;
      case 5:
        if (_eqUnits(name, 'range')) return range;
        if (_eqUnits(name, 'allow')) return allow;
      case 6:
        if (_eqUnits(name, 'cookie')) return cookie;
        if (_eqUnits(name, 'accept')) return accept;
        if (_eqUnits(name, 'expect')) return expect;
        if (_eqUnits(name, 'origin')) return origin;
        if (_eqUnits(name, 'server')) return server;
        if (_eqUnits(name, 'pragma')) return pragma;
      case 7:
        if (_eqUnits(name, 'upgrade')) return upgrade;
        if (_eqUnits(name, 'expires')) return expires;
        if (_eqUnits(name, 'trailer')) return trailer;
        if (_eqUnits(name, 'referer')) return referer;
        if (_eqUnits(name, 'alt-svc')) return altSvc;
        if (_eqUnits(name, 'sec-gpc')) return secGpc;
        if (_eqUnits(name, 'warning')) return warning;
      case 8:
        if (_eqUnits(name, 'if-match')) return ifMatch;
        if (_eqUnits(name, 'if-range')) return ifRange;
        if (_eqUnits(name, 'location')) return location;
        if (_eqUnits(name, 'alt-used')) return altUsed;
        if (_eqUnits(name, 'priority')) return priority;
      case 9:
        if (_eqUnits(name, 'forwarded')) return forwarded;
        if (_eqUnits(name, 'expect-ct')) return expectCt;
        if (_eqUnits(name, 'report-to')) return reportTo;
        if (_eqUnits(name, 'save-data')) return saveData;
        if (_eqUnits(name, 'sec-ch-ua')) return secChUa;
        if (_eqUnits(name, 'x-real-ip')) return xRealIp;
      case 10:
        if (_eqUnits(name, 'user-agent')) return userAgent;
        if (_eqUnits(name, 'connection')) return connection;
        if (_eqUnits(name, 'set-cookie')) return setCookie;
        if (_eqUnits(name, 'early-data')) return earlyData;
        if (_eqUnits(name, 'keep-alive')) return keepAlive;
      case 11:
        if (_eqUnits(name, 'retry-after')) return retryAfter;
        if (_eqUnits(name, 'accept-post')) return acceptPost;
        if (_eqUnits(name, 'content-md5')) return contentMd5;
      case 12:
        if (_eqUnits(name, 'content-type')) return contentType;
        if (_eqUnits(name, 'max-forwards')) return maxForwards;
        if (_eqUnits(name, 'x-powered-by')) return xPoweredBy;
        if (_eqUnits(name, 'accept-patch')) return acceptPatch;
        if (_eqUnits(name, 'x-csrf-token')) return xCsrfToken;
        if (_eqUnits(name, 'x-request-id')) return xRequestId;
      case 13:
        if (_eqUnits(name, 'authorization')) return authorization;
        if (_eqUnits(name, 'if-none-match')) return ifNoneMatch;
        if (_eqUnits(name, 'cache-control')) return cacheControl;
        if (_eqUnits(name, 'content-range')) return contentRange;
        if (_eqUnits(name, 'last-modified')) return lastModified;
        if (_eqUnits(name, 'accept-ranges')) return acceptRanges;
        if (_eqUnits(name, 'server-timing')) return serverTiming;
      case 14:
        if (_eqUnits(name, 'content-length')) return contentLength;
        if (_eqUnits(name, 'sec-fetch-dest')) return secFetchDest;
        if (_eqUnits(name, 'sec-fetch-mode')) return secFetchMode;
        if (_eqUnits(name, 'sec-fetch-site')) return secFetchSite;
        if (_eqUnits(name, 'accept-charset')) return acceptCharset;
      case 15:
        if (_eqUnits(name, 'accept-encoding')) return acceptEncoding;
        if (_eqUnits(name, 'accept-language')) return acceptLanguage;
        if (_eqUnits(name, 'x-forwarded-for')) return xForwardedFor;
        if (_eqUnits(name, 'referrer-policy')) return referrerPolicy;
        if (_eqUnits(name, 'clear-site-data')) return clearSiteData;
        if (_eqUnits(name, 'x-frame-options')) return xFrameOptions;
      case 16:
        if (_eqUnits(name, 'content-encoding')) return contentEncoding;
        if (_eqUnits(name, 'content-language')) return contentLanguage;
        if (_eqUnits(name, 'content-location')) return contentLocation;
        if (_eqUnits(name, 'www-authenticate')) return wwwAuthenticate;
        if (_eqUnits(name, 'proxy-connection')) return proxyConnection;
        if (_eqUnits(name, 'sec-ch-ua-mobile')) return secChUaMobile;
        if (_eqUnits(name, 'x-forwarded-host')) return xForwardedHost;
        if (_eqUnits(name, 'x-forwarded-port')) return xForwardedPort;
        if (_eqUnits(name, 'x-requested-with')) return xRequestedWith;
        if (_eqUnits(name, 'x-xss-protection')) return xXssProtection;
      case 17:
        if (_eqUnits(name, 'if-modified-since')) return ifModifiedSince;
        if (_eqUnits(name, 'transfer-encoding')) return transferEncoding;
        if (_eqUnits(name, 'sec-websocket-key')) return secWebsocketKey;
        if (_eqUnits(name, 'x-forwarded-proto')) return xForwardedProto;
      case 18:
        if (_eqUnits(name, 'proxy-authenticate')) return proxyAuthenticate;
        if (_eqUnits(name, 'permissions-policy')) return permissionsPolicy;
        if (_eqUnits(name, 'sec-ch-ua-platform')) return secChUaPlatform;
      case 19:
        if (_eqUnits(name, 'if-unmodified-since')) return ifUnmodifiedSince;
        if (_eqUnits(name, 'proxy-authorization')) return proxyAuthorization;
        if (_eqUnits(name, 'content-disposition')) return contentDisposition;
        if (_eqUnits(name, 'authentication-info')) return authenticationInfo;
        if (_eqUnits(name, 'timing-allow-origin')) return timingAllowOrigin;
      case 20:
        if (_eqUnits(name, 'sec-websocket-accept')) return secWebsocketAccept;
      case 21:
        if (_eqUnits(name, 'sec-websocket-version')) return secWebsocketVersion;
      case 22:
        if (_eqUnits(name, 'access-control-max-age'))
          return accessControlMaxAge;
        if (_eqUnits(name, 'sec-websocket-protocol'))
          return secWebsocketProtocol;
        if (_eqUnits(name, 'x-content-type-options'))
          return xContentTypeOptions;
        if (_eqUnits(name, 'x-dns-prefetch-control'))
          return xDnsPrefetchControl;
      case 23:
        if (_eqUnits(name, 'content-security-policy'))
          return contentSecurityPolicy;
      case 24:
        if (_eqUnits(name, 'sec-websocket-extensions'))
          return secWebsocketExtensions;
      case 25:
        if (_eqUnits(name, 'strict-transport-security'))
          return strictTransportSecurity;
        if (_eqUnits(name, 'upgrade-insecure-requests'))
          return upgradeInsecureRequests;
      case 26:
        if (_eqUnits(name, 'cross-origin-opener-policy'))
          return crossOriginOpenerPolicy;
      case 27:
        if (_eqUnits(name, 'access-control-allow-origin'))
          return accessControlAllowOrigin;
      case 28:
        if (_eqUnits(name, 'access-control-allow-methods'))
          return accessControlAllowMethods;
        if (_eqUnits(name, 'access-control-allow-headers'))
          return accessControlAllowHeaders;
        if (_eqUnits(name, 'cross-origin-resource-policy'))
          return crossOriginResourcePolicy;
        if (_eqUnits(name, 'cross-origin-embedder-policy'))
          return crossOriginEmbedderPolicy;
      case 29:
        if (_eqUnits(name, 'access-control-request-method'))
          return accessControlRequestMethod;
        if (_eqUnits(name, 'access-control-expose-headers'))
          return accessControlExposeHeaders;
      case 30:
        if (_eqUnits(name, 'access-control-request-headers'))
          return accessControlRequestHeaders;
      case 32:
        if (_eqUnits(name, 'access-control-allow-credentials'))
          return accessControlAllowCredentials;
      case 35:
        if (_eqUnits(name, 'content-security-policy-report-only'))
          return contentSecurityPolicyReportOnly;
    }
    return null;
  }
}

/// Case-insensitive match of `bytes[start..]` against the lowercase ASCII
/// [expected]. Every known name is letters, digits and `-`.
bool _eqBytes(final Uint8List bytes, final int start, final String expected) {
  for (var i = 0; i < expected.length; i++) {
    if (!_eqFolded(bytes[start + i], expected.codeUnitAt(i))) return false;
  }
  return true;
}

bool _eqUnits(final String name, final String expected) {
  for (var i = 0; i < expected.length; i++) {
    if (!_eqFolded(name.codeUnitAt(i), expected.codeUnitAt(i))) return false;
  }
  return true;
}

/// Whether [c] is [expected] or its uppercase. Only a letter folds:
/// `| 0x20` also takes CR to `-` and 0x10-0x19 to the digits.
@pragma('vm:prefer-inline')
bool _eqFolded(final int c, final int expected) =>
    c == expected || (expected >= 0x61 && (c | 0x20) == expected);

/// RFC 9110 5.6.2 tchar.
bool _isTchar(final int c) {
  if (c >= 0x30 && c <= 0x39) return true; // 0-9
  if (c >= 0x41 && c <= 0x5a) return true; // A-Z
  if (c >= 0x61 && c <= 0x7a) return true; // a-z
  switch (c) {
    case 0x21: // !
    case 0x23: // #
    case 0x24: // $
    case 0x25: // %
    case 0x26: // &
    case 0x27: // '
    case 0x2a: // *
    case 0x2b: // +
    case 0x2d: // -
    case 0x2e: // .
    case 0x5e: // ^
    case 0x5f: // _
    case 0x60: // `
    case 0x7c: // |
    case 0x7e: // ~
      return true;
  }
  return false;
}
