// Generates lib/src/header_name.dart from tool/header_names.txt.
//
//   dart run tool/generate_header_names.dart
//
// The line number in the list is the id, so the list is append only.
import 'dart:io';

import 'package:dart_style/dart_style.dart';
import 'package:pub_semver/pub_semver.dart';

void main() {
  final root = File.fromUri(Platform.script).parent.parent;
  final names = File('${root.path}/tool/header_names.txt')
      .readAsLinesSync()
      .map((final line) => line.trim())
      .where((final line) => line.isNotEmpty && !line.startsWith('#'))
      .toList();

  final duplicates = names.toSet().length != names.length;
  if (duplicates) throw StateError('header_names.txt has a duplicate');
  for (final name in names) {
    if (name != name.toLowerCase() || !_isToken(name)) {
      throw StateError('"$name" is not a lowercase token');
    }
  }

  final source = _source(names);
  final formatted = DartFormatter(
    // should match lower bound in pubspec.yaml
    languageVersion: Version(3, 10, 0),
  ).format(source);
  File('${root.path}/lib/src/header_name.dart').writeAsStringSync(formatted);
  stdout.writeln('Wrote ${names.length} header names');
}

bool _isToken(final String s) =>
    RegExp(r"^[-!#$%&'*+.^_`|~0-9a-z]+$").hasMatch(s);

/// `content-type` becomes `contentType`.
String _identifier(final String name) {
  final parts = name.split('-');
  return parts.first +
      parts
          .skip(1)
          .map((final p) => p[0].toUpperCase() + p.substring(1))
          .join();
}

String _source(final List<String> names) {
  final constants = [
    for (final (id, name) in names.indexed)
      "  /// `$name`\n  static const ${_identifier(name)} = HeaderName._($id, '$name');",
  ].join('\n\n');

  final table = [
    for (final name in names) '    ${_identifier(name)},',
  ].join('\n');

  final byLength = <int, List<String>>{};
  for (final name in names) {
    byLength.putIfAbsent(name.length, () => []).add(name);
  }
  final lengths = byLength.keys.toList()..sort();
  final bytesCases = [
    for (final length in lengths)
      '      case $length:\n'
          '${[for (final name in byLength[length]!) "        if (_eqBytes(bytes, start, '$name')) return ${_identifier(name)};"].join('\n')}',
  ].join('\n');
  final unitsCases = [
    for (final length in lengths)
      '      case $length:\n'
          '${[for (final name in byLength[length]!) "        if (_eqUnits(name, '$name')) return ${_identifier(name)};"].join('\n')}',
  ].join('\n');

  return '''
// GENERATED by tool/generate_header_names.dart from tool/header_names.txt.
// Do not edit by hand.

import 'dart:typed_data';

/// An interned HTTP header name.
///
/// Known names have a stable small [id], so a store can index them without
/// hashing strings, and compare them by [id] alone. An unknown name has id
/// -1 and compares by its lowercase text, so it still works as a map key.
///
/// Names are ASCII case-insensitive on the wire (RFC 9110 5.1). [lower] is
/// the canonical form. The [id] of a known name is part of the public API
/// and never changes.
final class HeaderName {
  /// Stable small id of a known name, or -1.
  final int id;

  /// The canonical lowercase name.
  final String lower;

  const HeaderName._(this.id, this.lower);

  /// A name outside the known table, from a lowercase token.
  ///
  /// Use [lookup] for a name that may be known or may carry uppercase. This
  /// constructor exists for const contexts such as a `const HeaderAccessor`
  /// on a custom header.
  const HeaderName.custom(this.lower)
    : id = -1,
      assert(lower != '', 'A header name is not empty');

  /// The known name for [name], or a fresh unknown name.
  ///
  /// Throws [FormatException] when [name] is not an HTTP token.
  static HeaderName lookup(final String name) {
    final known = _lookupUnits(name);
    if (known != null) return known;
    if (!isToken(name)) {
      throw FormatException('Invalid header name', name);
    }
    return HeaderName._(-1, name.toLowerCase());
  }

  /// The known name spelled by `bytes[start..end)`, or null.
  ///
  /// Allocates nothing. Adapters call this while indexing a request head.
  static HeaderName? lookupBytes(
    final Uint8List bytes,
    final int start,
    final int end,
  ) {
    switch (end - start) {
$bytesCases
    }
    return null;
  }

  /// Every known name, indexed by [id].
  static const known = <HeaderName>[
$table
  ];

  /// True if [s] is a non-empty HTTP token (RFC 9110 5.6.2).
  static bool isToken(final String s) {
    if (s.isEmpty) return false;
    for (var i = 0; i < s.length; i++) {
      if (!_isTchar(s.codeUnitAt(i))) return false;
    }
    return true;
  }

  /// True if [c] is a `tchar` code unit (RFC 9110 5.6.2).
  static bool isTchar(final int c) => _isTchar(c);

  @override
  bool operator ==(final Object other) =>
      other is HeaderName &&
      (id >= 0 ? id == other.id : (other.id < 0 && lower == other.lower));

  @override
  int get hashCode => id >= 0 ? id : lower.hashCode;

  @override
  String toString() => lower;

$constants

  static HeaderName? _lookupUnits(final String name) {
    switch (name.length) {
$unitsCases
    }
    return null;
  }
}

/// Case-insensitive match of `bytes[start..]` against the lowercase ASCII
/// [expected]. Every known name is letters, digits and `-`.
bool _eqBytes(final Uint8List bytes, final int start, final String expected) {
  for (var i = 0; i < expected.length; i++) {
    if (!_eqFolded(bytes[start + i], expected.codeUnitAt(i))) return false;
  }
  return true;
}

bool _eqUnits(final String name, final String expected) {
  for (var i = 0; i < expected.length; i++) {
    if (!_eqFolded(name.codeUnitAt(i), expected.codeUnitAt(i))) return false;
  }
  return true;
}

/// Whether [c] is [expected] or its uppercase. Only a letter folds:
/// `| 0x20` also takes CR to `-` and 0x10-0x19 to the digits.
@pragma('vm:prefer-inline')
bool _eqFolded(final int c, final int expected) =>
    c == expected || (expected >= 0x61 && (c | 0x20) == expected);

/// RFC 9110 5.6.2 tchar.
bool _isTchar(final int c) {
  if (c >= 0x30 && c <= 0x39) return true; // 0-9
  if (c >= 0x41 && c <= 0x5a) return true; // A-Z
  if (c >= 0x61 && c <= 0x7a) return true; // a-z
  switch (c) {
    case 0x21: // !
    case 0x23: // #
    case 0x24: // \$
    case 0x25: // %
    case 0x26: // &
    case 0x27: // '
    case 0x2a: // *
    case 0x2b: // +
    case 0x2d: // -
    case 0x2e: // .
    case 0x5e: // ^
    case 0x5f: // _
    case 0x60: // `
    case 0x7c: // |
    case 0x7e: // ~
      return true;
  }
  return false;
}
''';
}
